name: portfolio
description: A Flutter portfolio website for Israr Ahmed
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI / Fonts
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.2

  # URL Launcher
  url_launcher: ^6.3.1

  # âœ… Pin to version that works with Flutter 3.24 and Dart 3.4
  font_awesome_flutter: 10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.png
